#!/usr/bin/env ruby
require 'rubygems'
require 'redcarpet'
require 'tempfile'

# Settings (Change this to suit your needs)
browser = ENV['BROWSER'] ? ENV['BROWSER'] : 'xdg-open'
md_render =  Redcarpet::Render::XHTML
md_ext = {
  :no_intra_emphasis => true, :fenced_code_blocks => true,
  :superscript => true, :space_after_headers => true
}

overwrite = false

# Abort if no argument passed.
abort("Usage: markdown <file.md>") unless ARGV[0]

# Set path if file exists (or abort)
abort("File does not exist") unless File.exist?(ARGV[0])
path = ARGV[0]

# Render markdown
markdown = Redcarpet::Markdown.new(md_render, md_ext)
rendered = markdown.render(File.read(path))

# Write to html path
tmp_path = '/tmp/' + path.split('/')[-1].split('.')[0] + '.html'
html_path = ARGV[1] ? ARGV[1] : tmp_path

if html_path != tmp_path && html_path[-5..-1] != '.html'
  if File.directory?(html_path)
    html_path += '/' if html_path[-1] != '/'
    html_path += path.split('/')[-1].split('.')[0] + '.html' 
  else
    html_path += '/' + path.split('/')[-1].split('.')[0] + '.html'
  end
end

if File.exist?(html_path)
  print "That file exists. Overwrite? [y/n]"
  overwrite = $stdin.gets.chomp
  overwrite = true if overwrite[0] == default
end

if overwrite || !File.exist?(html_path)
  f = File.new(html_path, 'w'); f.write(rendered); f.close

  `#{browser} #{html_path} >/dev/null 2>&1`
end